### ISSUE TITLE
Update to 1.9.6-ynh1 failed (yarn-cache/git related error)

### ISSUE THREAD

**Issue by rmueck** [YunoHost-Apps/hedgedoc_ynh#50]
Update `1.9.5~ynh1 to 1.9.6~ynh1` failed

### Context
- Hardware: VPS
- YunoHost version: `11.0.10.2 (stable)`
- I have access to my server: `ssh`

### Steps to reproduce
~~~sh
    sudo yunohost app upgrade hedgedoc
~~~

### Expected behavior
Upgrade sucessful

### Logs
[Logs](https://paste.yunohost.org/raw/ukumajexip)

**Comment by cichy1173** [comment]
Hello! I have the same issue. 

https://paste.yunohost.org/raw/dobifuzova

**Comment by isAAAc** [comment]
same here too
hedgedoc upgrade: 1.9.5~ynh1 to 1.9.6~ynh1

yunohost -v
```
yunohost: 
  repo: stable
  version: 11.0.10.2
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
```

https://paste.yunohost.org/raw/fapipicohu
