### ISSUE TITLE
upgrade 1.9.6~ynh2 to 1.9.7~ynh2 is failing

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/hedgedoc_ynh#60]
### Describe the bug

upgrade to 1.9.7~ynh2 is failing

### Context

- Hardware: *VPS bought online / Old laptop or computer / Raspberry Pi at home / Internet Cube with VPN / Other ARM board / ...*
- YunoHost version: 
```
root@gourzoot:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.1.15
yunohost-admin: 
  repo: stable
  version: 11.1.7
moulinette: 
  repo: stable
  version: 11.1.4
ssowat: 
  repo: stable
  version: 11.1.4
```

- I have access to my server: *Through SSH | through the webadmin *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no *
- Using, or trying to install package version/branch: `1.9.7~ynh2`
- If upgrading, current package version: `1.9.6~ynh2`

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    # yunohost app upgrade hedgedoc
    ```
### Expected behavior

i expect an upgrade to `1.9.7~ynh2`

### Logs

* first try:
https://paste.yunohost.org/raw/xoruxuzeha

i clean yarn cache and retry: 
```
root@gourzoot:~# sudo yarn cache clean
yarn cache v1.22.19
success Cleared cache.
Done in 0.07s.
```
*  second try is running
